# Generated by Django 2.2.13 on 2020-06-18 22:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(default=datetime.date.today, editable=False)),
                ('created_when', models.DateField(default=datetime.date.today, editable=False)),
                ('disabled', models.BooleanField(default=False, editable=False)),
                ('disabled_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('disabled_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('disabled_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to disable this product')),
                ('dropped', models.BooleanField(default=False, editable=False)),
                ('dropped_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('dropped_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('dropped_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to drop this object')),
                ('description_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('description_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('address_line1', models.TextField(default=None, max_length=1024, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Address line 1')),
                ('address_line2', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Address line 2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(default=datetime.date.today, editable=False)),
                ('created_when', models.DateField(default=datetime.date.today, editable=False)),
                ('disabled', models.BooleanField(default=False, editable=False)),
                ('disabled_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('disabled_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('disabled_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to disable this product')),
                ('dropped', models.BooleanField(default=False, editable=False)),
                ('dropped_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('dropped_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('dropped_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to drop this object')),
                ('description_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('description_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('email', models.EmailField(default=None, max_length=254, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(254)], verbose_name='Correo Electrónico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(default=datetime.date.today, editable=False)),
                ('created_when', models.DateField(default=datetime.date.today, editable=False)),
                ('disabled', models.BooleanField(default=False, editable=False)),
                ('disabled_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('disabled_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('disabled_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to disable this product')),
                ('dropped', models.BooleanField(default=False, editable=False)),
                ('dropped_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('dropped_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('dropped_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to drop this object')),
                ('description_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('description_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('phone', models.CharField(default=None, max_length=13, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)], verbose_name='Cell phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(default=datetime.date.today, editable=False)),
                ('created_when', models.DateField(default=datetime.date.today, editable=False)),
                ('disabled', models.BooleanField(default=False, editable=False)),
                ('disabled_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('disabled_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('disabled_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to disable this product')),
                ('dropped', models.BooleanField(default=False, editable=False)),
                ('dropped_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('dropped_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('dropped_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to drop this object')),
                ('description_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('description_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('name', models.CharField(choices=[('1', 'Facebook'), ('2', 'Twitter'), ('3', 'Instagram'), ('4', 'Snapchat')], default=None, max_length=1, verbose_name='Name')),
                ('value', models.CharField(default=None, max_length=254, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(254)], verbose_name='URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
