# Generated by Django 2.2.13 on 2020-07-21 23:28

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(default=datetime.datetime(2020, 7, 21, 23, 28, 4, 145955), editable=False)),
                ('created_when', models.DateField(default=datetime.datetime(2020, 7, 21, 23, 28, 4, 146001), editable=False)),
                ('disabled', models.BooleanField(default=False, editable=False)),
                ('disabled_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('disabled_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('disabled_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to disable this product')),
                ('dropped', models.BooleanField(default=False, editable=False)),
                ('dropped_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('dropped_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('dropped_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to drop this object')),
                ('description_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_es', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('description_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Description')),
                ('notes_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Notes')),
                ('comments_en', models.TextField(blank=True, default=None, max_length=1024, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(1024)], verbose_name='Comments')),
                ('code', models.CharField(default=None, max_length=4, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(4)], verbose_name='Code')),
                ('created_by_user', models.ForeignKey(db_column='created_by_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='scale_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Scale',
                'verbose_name_plural': 'Scales',
            },
        ),
    ]
