# Generated by Django 2.2.13 on 2020-06-18 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('symptons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='disorder_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='disorder',
            name='symptons',
            field=models.ManyToManyField(to='symptons.Sympton'),
        ),
    ]
