# Generated by Django 2.2.13 on 2020-07-21 23:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axis', '0003_auto_20200721_2328'),
        ('disorders', '0002_auto_20200618_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder',
            name='axis',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='axis.Axis', verbose_name='Axis'),
        ),
        migrations.AddField(
            model_name='disorder',
            name='parent',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='disorders.Disorder', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='disorder',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2020, 7, 21, 23, 28, 4, 145955), editable=False),
        ),
        migrations.AlterField(
            model_name='disorder',
            name='created_when',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 23, 28, 4, 146001), editable=False),
        ),
        migrations.AlterField(
            model_name='disorder',
            name='symptons',
            field=models.ManyToManyField(default=None, to='symptons.Sympton', verbose_name='Symptons'),
        ),
    ]
