# Generated by Django 2.2.13 on 2020-06-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
        ('medicaments', '0002_medicament_created_by_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='medicaments',
            field=models.ManyToManyField(to='medicaments.Medicament'),
        ),
    ]
