# Generated by Django 2.2.13 on 2020-06-18 22:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TimeField(default=datetime.date.today, editable=False)),
                ('created_when', models.DateField(default=datetime.date.today, editable=False)),
                ('disabled', models.BooleanField(default=False, editable=False)),
                ('disabled_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('disabled_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('disabled_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to disable this product')),
                ('dropped', models.BooleanField(default=False, editable=False)),
                ('dropped_at', models.TimeField(blank=True, default=None, editable=False, null=True)),
                ('dropped_when', models.DateField(blank=True, default=None, editable=False, null=True)),
                ('dropped_reason', models.CharField(blank=True, default=None, editable=False, max_length=1024, null=True, verbose_name='Specify the reason to drop this object')),
                ('last_name', models.CharField(default=None, max_length=254, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(254)], verbose_name='Last name')),
                ('mothers_last_name', models.CharField(blank=True, default=None, max_length=254, null=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(254)], verbose_name='Mothers last name')),
                ('first_name', models.CharField(default=None, max_length=254, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(254)], verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=254, null=True, verbose_name='Middle name')),
                ('gender', models.CharField(choices=[(' ', '-- Prefer not to say --'), ('M', 'Male'), ('F', 'Female')], default=None, max_length=1, verbose_name='Gender')),
                ('dob', models.DateField(default=None, verbose_name='Date of birth')),
                ('addresses', models.ManyToManyField(to='catalogues.PersonAddress')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
