# Generated by Django 2.2.13 on 2020-06-18 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('symptons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0002_auto_20200618_2224'),
        ('treatments', '0001_initial'),
        ('disorders', '0002_auto_20200618_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='patient_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='patient',
            name='disorders',
            field=models.ManyToManyField(to='disorders.Disorder'),
        ),
        migrations.AddField(
            model_name='patient',
            name='emails',
            field=models.ManyToManyField(to='catalogues.PersonEmail'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phones',
            field=models.ManyToManyField(to='catalogues.PersonPhone'),
        ),
        migrations.AddField(
            model_name='patient',
            name='social_networks',
            field=models.ManyToManyField(to='catalogues.SocialNetwork'),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptons',
            field=models.ManyToManyField(to='symptons.Sympton'),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatments',
            field=models.ManyToManyField(to='treatments.Treatment'),
        ),
    ]
