# Generated by Django 2.2.13 on 2020-07-21 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200618_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2020, 7, 21, 23, 28, 4, 145955), editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_when',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 23, 28, 4, 146001), editable=False),
        ),
    ]
