# Generated by Django 2.2.13 on 2020-06-14 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0002_medicament_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2020, 6, 14, 9, 48, 49, 412617), editable=False),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='created_when',
            field=models.DateField(default=datetime.datetime(2020, 6, 14, 9, 48, 49, 412666), editable=False),
        ),
    ]
