# Generated by Django 2.2.13 on 2020-06-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        migrations.swappable_dependency(settings.CITIES_CITY_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='socialnetwork_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='personphone',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='personphone_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='personemail',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='personemail_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='city',
            field=models.ForeignKey(db_column='city_id', default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.CITIES_CITY_MODEL, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='personaddress',
            name='created_by_user',
            field=models.ForeignKey(db_column='created_by_user', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='personaddress_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
